server:
  port: 8887

github:
  Client:
    id: 9f4a298ad500724a3733
    secret: 392bd327d07268926fed3e694c02e2e7dcca47ec
  Redirect:
    uri: http://localhost:8887/callback

spring:
  datasource:
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/chatliu


mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰
  type-aliases-package: com.winsum.chatliu.model #pojo位置
  mapper-locations: classpath:mapper/*Mapper.xml #mapper.xml位置
